create table laplace.latest_alex_reserve_pools (
  token_deployer_address varchar not null,
  token_name varchar not null,
  block_height integer not null,
  burn_block_time integer not null,
  activation_block integer not null,
  reward_cycle_length integer not null,
  token_halving_cycle integer not null,
  current_cycle integer not null,
  reserved_balance bigint not null,
  coinbase_amount_1 bigint not null,
  coinbase_amount_2 bigint not null,
  coinbase_amount_3 bigint not null,
  coinbase_amount_4 bigint not null,
  coinbase_amount_5 bigint not null,
  apower_multiplier bigint not null,
  staking_stats jsonb not null,
  earning_preview jsonb not null,
  dual_yield_token_deployer_address varchar,
  dual_yield_token_name varchar,
  dual_yield_token_multiplier bigint,
  sync_at timestamp with time zone not null,
  primary key (token_deployer_address, token_name)
);
