DROP MATERIALIZED VIEW IF EXISTS "laplace"."farming_details";
DROP MATERIALIZED VIEW IF EXISTS "laplace"."liquidity_details";
DROP MATERIALIZED VIEW IF EXISTS "laplace"."wstx_alex_pool_volume";
DROP MATERIALIZED VIEW IF EXISTS "laplace"."wstx_wbtc_pool_volume";
DROP MATERIALIZED VIEW IF EXISTS "laplace"."ytp_liquidity";
DROP MATERIALIZED VIEW IF EXISTS "laplace"."fwp_liquidity";
DROP MATERIALIZED VIEW IF EXISTS "laplace"."fwp_liquidity";
DROP VIEW IF EXISTS "laplace"."liquidity_provider_fee";
DROP table IF EXISTS "laplace"."pool_volume";
DROP table IF EXISTS "laplace"."pool_liquidity";
DROP table IF EXISTS "laplace"."pool_details_crp";
DROP table IF EXISTS "laplace"."pool_details_fwp";
DROP table IF EXISTS "laplace"."pool_details_ytp";
DROP table IF EXISTS "laplace"."pool_details_crp";
DROP table IF EXISTS "laplace"."pool_details_fwp_map_entry";
DROP table IF EXISTS "laplace"."pool_details_swp_map_entry";
DROP table IF EXISTS "laplace"."dynamic_ltv_crp";
DROP table IF EXISTS "laplace"."dynamic_position_crp";
DROP table IF EXISTS "laplace"."dynamic_price_ytp";
DROP table IF EXISTS "laplace"."dynamic_y_given_x_fwp";
DROP table IF EXISTS "laplace"."dynamic_yield_ytp";
DROP table IF EXISTS "laplace"."static_data_fwp";
DROP table IF EXISTS "laplace"."static_data_ytp";

